name       : magic-wormhole
version    : 0.10.5
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/m/magic-wormhole/magic-wormhole-0.10.5.tar.gz : 9558ea1f3551e535deec3462cd5c8391cb32ebb12ecd8b40b36861dbee4917ee
license    : MIT
component  : network
summary    : Securely transfer data between computers
description: "Securely transfer data between computers \n"
rundeps    :
    - python-autobahn
    - python-cffi
    - python-click
    - python-hkdf
    - python-humanize
    - python-idna
    - python-pynacl
    - python-service-identity
    - python-spake2
    - python-tqdm
    - python-txtorcon
setup      : |
    %python3_setup
install    : |
    %python3_install
