name       : magic-wormhole
version    : 0.12.0
release    : 3
source     :
    - https://github.com/warner/magic-wormhole/archive/0.12.0.tar.gz : 5522184ab995a22ff72bf9019e54cb7b5e7f0f3308c251f121da15a198afe1d9
license    : MIT
component  : network
summary    : Securely transfer data between computers
description: |
    Securely transfer data between computers.
rundeps    :
    - python-autobahn
    - python-cffi
    - python-click
    - python-hkdf
    - python-humanize
    - python-idna
    - python-pynacl
    - python-service-identity
    - python-spake2
    - python-tqdm
    - python-txtorcon
setup      : |
    %python3_setup
install    : |
    %python3_install
